### ISSUE TITLE
'dpd stop' - can not be  reached  though stop.js is implemented

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd-cli#10]
STOP action is not get caught in bin/dpd.

cli.program
  .command('showkey')
  .description('\tshows current key for connecting to remote dashboard (./.dpd/keys.json)')
  .action(cli.showkey);

cli.program
  .command('*')
  .description('\t[default] start the server in the current project in development mode\n' +
               '\twith an interactive shell/repl for interacting with the running server\n' +
               '\te.g. dpd (starts server in current directory),\n' +
               '\t     dpd my-app/app.dpd (starts app from file)')
  .action(cli.start);

**Comment by moorthi07** [comment]
Also dpd command throws error in 'stop.js'

>dpd
This directory does not contain a Deployd app!
Use "dpd create <appname>" to create a new app
or use "dpd path/to/app.dpd" to start an app in another directory
C:\Users\imadmin\Downloads\deployd-cli-master\lib\cli\stop.js:9
  if (program.wait) {
      ^

ReferenceError: program is not defined
    at stop (C:\Users\imadmin\Downloads\deployd-cli-master\lib\cli\stop.js:9:7)
    at Object.start (C:\Users\imadmin\Downloads\deployd-cli-master\lib\cli\start.js:109:5)
    at Object.<anonymous> (C:\Users\imadmin\Downloads\deployd-cli-master\bin\dpd:55:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)

**Comment by moorthi07** [comment]
1. To stop running dpd server  'use ctrl + c'  to exit (from dpd repl - the same).
2. program.wait - is fixed in PR #12
