### ISSUE TITLE
TypeError: program.password is not a function

### ISSUE THREAD

**Issue by moorthi07** [deployd/deployd-cli#7]
The environment:
MongoDB is secured , you need auth to the db in localhost.

Tried ,

> dpd -H 'localhost'  -P 27017 -a

Here is the steps.js code where error is thrown.

>     // Check if there are no steps left
>     if (steps.length === 0) {
>       // Throw uncaught errors
>       if (arguments[0]) {
>         throw arguments[0];
>       }
>       return;
>     }
> 

// Error:

> 
> C:\sites\dpd_tutorial>dpd -H 'localhost'  -P 27017 -a
> deployd CLI version 0.0.2
> starting deployd
> TypeError: program.password is not a function
>     at Function.<anonymous> (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\start.js:78:29)
>     at next (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:51:23)
>     at next (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:54:7)
>     at Step (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:122:3)
>     at Object.start (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\start.js:63:13)
>     at Object.<anonymous> (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\bin\dpd:55:40)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
>     at Module.load (module.js:487:32)
>     at tryModuleLoad (module.js:446:12)
> Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deploy
> d.com/docs/basics/cli.html)
> C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:39
>         throw arguments[0];
>         ^
> 
> ReferenceError: program is not defined
>     at stop (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\stop.js:7:7)
>     at Function.startup (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\start.js:108:16)
>     at next (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:51:23)
>     at next (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:54:7)
>     at next (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:54:7)
>     at Step (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:122:3)
>     at Object.start (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\start.js:63:13)
>     at Object.<anonymous> (C:\Users\usr\AppData\Roaming\npm\node_modules\dpd-cli\bin\dpd:55:40)
>     at Module._compile (module.js:570:32)
>     at Object.Module._extensions..js (module.js:579:10)
> 
>

**Comment by moorthi07** [comment]
"commander": "^2.2.0", installs  "version": "2.10.0"   - doesn't support program.prompt / program.password.  (It is a breaking change in a sub version)

Tried 2.2.0 , still the same problem!

TypeError: program.password is not a function

**Comment by moorthi07** [comment]
dpd --host 'localhost:27017' -a    --- not working
 
   my-deployd-app>dpd --host 'localhost:27017' -a
deployd CLI version 0.0.2
starting deployd
Failed to start MongoDB (Make sure 'mongod' are in your $PATH or use dpd --mongod option. Ref: http://docs.deploy
d.com/docs/basics/cli.html)
C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:39
        throw arguments[0];
        ^

ReferenceError: program is not defined
    at stop (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\stop.js:7:7)
    at Function.startup (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\start.js:107:16)
    at next (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:51:23)
    at next (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:54:7)
    at next (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:54:7)
    at Step (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\node_modules\step\lib\step.js:122:3)
    at Object.start (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\lib\cli\start.js:63:13)
    at Object.<anonymous> (C:\Users\imadmin\AppData\Roaming\npm\node_modules\dpd-cli\bin\dpd:55:40)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by moorthi07** [comment]
fixed in PR #12
